import NavBar from '@/components/NavBar'
import './globals.css'
import styles from "./page.module.css";
import { Inter, Montserrat } from 'next/font/google'
import { UserProvider } from '@/context/UserContext';

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Bitcoin Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><NavBar /> {/* common layout like navbars goes in parent layout */}
        <main className={styles.main}><UserProvider>{children}</UserProvider></main> {/* can still wrap all children in context provider */}
        <footer style={{background: '#333', color:'#fff', textAlign: 'center'}}>Copyright &copy; 2023</footer>
      </body>
    </html>
  )
}